### ISSUE TITLE
non-obvious error when passing invalid 'previous' or 'next' tokens

### ISSUE THREAD

**Issue by bradvogel** [mixmaxhq/mongo-cursor-pagination#118]
When passing an incorrect value such as 'next=NOT_REAL_TOKEN', this library will throw the exception `Unexpected token } in JSON at position 0`. It would be better if it threw a more obvious error such as "Invalid valid for 'next'"

**Comment by mvibraim** [comment]
```
SyntaxError: Unexpected end of JSON input
  at JSON.parse (<anonymous>)
  at Object.module.exports.parse (/usr/src/app/node_modules/mongodb-extended-json/lib/index.js:39:21)
  at Object.module.exports.decode (/usr/src/app/node_modules/mongo-cursor-pagination/src/utils/bsonUrlEncoding.js:14:16)
  at sanitizeParams (/usr/src/app/node_modules/mongo-cursor-pagination/src/utils/sanitizeParams.js:8:50)
  at module.exports (/usr/src/app/node_modules/mongo-cursor-pagination/src/find.js:33:11)
  at Object.findWithReq (/usr/src/app/node_modules/mongo-cursor-pagination/src/findWithReq.js:27:10)
```

JSON input: `{"$oid":"5ea922dce5bb260409f14010"`
