### ISSUE TITLE
_id as string regression

### ISSUE THREAD

**Issue by Marsup** [mixmaxhq/mongo-cursor-pagination#196]
Hello !

The change from `mongodb-extended-json` to `bson` between version 7.2.0 and 7.3.0 apparently broke some of our queries.
We now get those errors:
```
Error: not an object instance
    at serializeDocument (./node_modules/mongo-cursor-pagination/node_modules/bson/lib/extended_json.js:304:53)
    at Object.stringify (./node_modules/mongo-cursor-pagination/node_modules/bson/lib/extended_json.js:192:7)
    at Object.module.exports.encode (./node_modules/mongo-cursor-pagination/src/utils/bsonUrlEncoding.js:11:33)
    at prepareResponse (./node_modules/mongo-cursor-pagination/src/utils/query.js:39:45)
    at module.exports (./node_modules/mongo-cursor-pagination/src/find.js:58:20)
```
Apparently `bson` refuses to double encode strings, where `"foobar"` would previously return `"\"foobar\""`, it now throws.
Should there be an exception in `bsonUrlEncoding.js` when it's already a string to proceed with `JSON.stringify` instead of `EJSON.stringify` ?

**Comment by bradvogel** [comment]
Thanks for filing.

Are you storing the `previous` or `next` cursors somewhere and passing them to a new version of mongo-cursor-pagination? 

Or if not, can you share an example of how a cursor encoded with mongo-cursor-pagination can get into this state?

**Comment by Marsup** [comment]
A single mongo-cursor-pagination version is used, back and forth between browser and server. Our `_id`s are strings, not ObjectIDs, so this is probably why it gets in this state. I can probably make up some reproduction but it's probably all there is to that.

**Comment by bradvogel** [comment]
Great catch. Fixed here https://github.com/mixmaxhq/mongo-cursor-pagination/pull/198

**Comment by Marsup** [comment]
This is exactly what I had in mind, thanks for making the patch!

**Comment by Marsup** [comment]
Thanks a lot for seeing it through !
