### ISSUE TITLE
Getting findAsCursor is not a function exception

### ISSUE THREAD

**Issue by BhaskaranR** [mixmaxhq/mongo-cursor-pagination#23]
```
TypeError: collection.findAsCursor is not a function
    at Object.<anonymous> (/Users/bhaskaran/Documents/ksoc-new/api-graphql/node_modules/mongo-cursor-pagination/dist/node/find.js:129:36)
    at next (native)
    at step (/Users/bhaskaran/Documents/ksoc-new/api-graphql/node_modules/mongo-cursor-pagination/dist/node/find.js:1:191)
    at /Users/bhaskaran/Documents/ksoc-new/api-graphql/node_modules/mongo-cursor-pagination/dist/node/find.js:1:437
```

appreciate any help to fix this.  cant find findAsCursor function in mongodb

**Comment by BhaskaranR** [comment]
sorry did not use mongoist
